name: MongoDB Pinger

on:
  schedule:
    - cron: "0 0 25 * *"
  workflow_dispatch: # Manual trigger button in GitHub Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Run MongoDB Pinger
        run: npx mongo-pinger@latest
        env:
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
